// import { Inter } from 'next/font/google'

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Tailwind's default `font-sans` already maps to a system stack */}
      <body className="font-sans antialiased">{children}</body>
    </html>
  )
}
